"""add questions and paper_questions tables

Revision ID: 4f5100746ebf
Revises: 0b5ad4de0f50
Create Date: 2026-06-05 19:44:13.999203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5100746ebf'
down_revision: Union[str, Sequence[str], None] = '0b5ad4de0f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False, comment='试卷ID'),
    sa.Column('question_id', sa.String(length=36), nullable=False, comment='题目ID'),
    sa.Column('section_label', sa.String(length=50), nullable=False, comment='大题标签'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('score', sa.Float(), nullable=False, comment='实际分值'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_questions_paper_id'), 'paper_questions', ['paper_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False, comment='学科'),
    sa.Column('grade', sa.String(length=10), nullable=False, comment='年级'),
    sa.Column('question_type', sa.String(length=20), nullable=False, comment='题型'),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='难度 1-5'),
    sa.Column('content', sa.Text(), nullable=False, comment='题目内容(HTML)'),
    sa.Column('options', sa.Text(), nullable=True, comment='选择题选项 JSON'),
    sa.Column('answer', sa.Text(), nullable=True, comment='答案/参考答案'),
    sa.Column('analysis', sa.Text(), nullable=True, comment='解析(HTML)'),
    sa.Column('score', sa.Float(), nullable=False, comment='默认分值'),
    sa.Column('knowledge_points', sa.Text(), nullable=False, comment='知识点 JSON 数组'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='来源: ai_generated/manual/batch_import'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: draft/published/archived'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='被引用次数'),
    sa.Column('created_by', sa.String(length=36), nullable=False, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_subject_grade_type', 'questions', ['subject', 'grade', 'question_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_questions_subject_grade_type', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_paper_questions_paper_id'), table_name='paper_questions')
    op.drop_table('paper_questions')
    # ### end Alembic commands ###
