"""add paper_template exam_type

Revision ID: 81cd0b8073dc
Revises: 1c5b122397f9
Create Date: 2026-05-31 23:09:44.162640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81cd0b8073dc'
down_revision: Union[str, Sequence[str], None] = '1c5b122397f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_templates', sa.Column('exam_type', sa.String(length=20), nullable=False, comment='考试类型: quiz=周测, midterm=期中, final=期末, general=通用'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_templates', 'exam_type')
    # ### end Alembic commands ###
