"""add total_score to paper_templates

Revision ID: b27c468c34f2
Revises: d9c7e2f1b1d3
Create Date: 2026-06-02 15:04:14.978233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27c468c34f2'
down_revision: Union[str, Sequence[str], None] = 'd9c7e2f1b1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_templates', sa.Column('total_score', sa.Float(), server_default=sa.text('100.0'), nullable=False, comment='试卷总分'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_templates', 'total_score')
    # ### end Alembic commands ###
