"""create knowledge_points table

Revision ID: d9c7e2f1b1d3
Revises: 81cd0b8073dc
Create Date: 2026-05-31 23:14:31.298906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c7e2f1b1d3'
down_revision: Union[str, Sequence[str], None] = '81cd0b8073dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_points',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False, comment='学科'),
    sa.Column('grade', sa.String(length=20), nullable=False, comment='年级'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='知识点名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject', 'grade', 'name', name='uq_kp_subject_grade_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_points')
    # ### end Alembic commands ###
